### ISSUE TITLE
Enforcing minimum number of observations for resampling in the high level interface for web processing

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#101]
I'm not sure how the automatic colocation engine handles stations with a very low number of valid observations. In the web interface, we now have some stations which only have a single valid data point for an entire year showing up. According to the docs, if the automatic colocator handles this the same way as the low-level colocator methods, these stations should be removed due to 

`pyaerocom.const.OBS_APPLY_TIME_RESAMPLE_CONSTRAINTS = True`

by default and the defaults being sensible

```
In: pya.const.OBS_MIN_NUM_RESAMPLE
Out:
{'yearly': {'monthly': 3},
 'monthly': {'daily': 7},
 'daily': {'hourly': 6},
 'hourly': {'minutely': 15}}
```

Setting a minimum number of observations in each resampling period is possible in Pyaerocom. From the docs: 
 
```
monthly_with_count = aod_data.resample('M').agg(['mean', 'count'])
invalid_mask = monthly_with_count['count'] < 15
monthly_with_count['mean'][invalid_mask] = np.nan
aod_monthly_min15d = monthly_with_count['mean']
aod_monthly_min15d.head()

```
It's also exposed in the low-level colocation methods, and done automatically with reasonable defaults unless specified not to.

**Comment by jgliss** [comment]
@hansbrenna you are correct, the default settings for temporal resampling are

```python
{'yearly': {'monthly': 3},
 'monthly': {'daily': 7},
 'daily': {'hourly': 6},
 'hourly': {'minutely': 15}}
```
and they are applied in the web processing if not specified differently in the evaluation config file, via `apply_time_resampling_constraints=True/False` and `min_num_obs` which may be a nested dictionary as above in the default case but can also be set to an integer (e.g. 2) in which case no step-wise resampling is done but rather *at least 2 valid data points in original resolution to get a value in the output resolution*.

So if you do not specify anything in the config file, the above nested resampling should be applied. The reason why this did not work properly for `GHOST.hourly` is probably due to #103.

**Comment by jgliss** [comment]
Removed label bug for now as I suspect this is due to #103 and also enhancement as fully flexible hierarchical resampling is already available also in highlevel routines. However, leaving this open until fully clarified.

**Comment by hansbrenna** [comment]
@jgliss your bug fix yesterday related to #103 seems to have fixed this issue.

**Comment by hansbrenna** [comment]
At least as far as properly enforcing the defaults. I haven't tested the full interface yet.

**Comment by jgliss** [comment]
@hansbrenna great to hear! Thanks! Maybe we can leave this open for a little longer to see if this was really the issue.
