### ISSUE TITLE
Picking up of colocated data objects should be tied to specific models

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#1161]
**Describe the bug**

The `obs_only` and `coldata_dir` used for an obs network can not handle multiple models as it stands. Maybe make `coldata_dir` into a `col_datadirs` dict in which the keys are `model_id`'s and the values are the directories for those coldata dirs. Then a obs-network is associated to a specific model. Need this to compare the same obs network against multiple models.

 - Pyaerocom version: v0.18.dev0
 - Computing platform: Linux
 - Configuration file (if applicable): `/lustre/storeB/users/lewisb/Python/Evaluations/aeroval/config/config_files`
 - Error message (if applicable): NA

**To Reproduce**
1. Run the config

**Comment by charlienegri** [comment]
if you mean the obs `only_json=True` option here, I ended up not using that in the end for the MOS exp, but I had edited the glob line https://github.com/metno/pyaerocom/blob/main-dev/pyaerocom/aeroval/experiment_processor.py#L63 and tested that it picks up the colocated data correctly if it's split into model-based subfolders (like we have for cams2_83)  

(basically with that line in place, I could have used that way instead of the global only_json, and I tested that it works for the standard statistics, but then I would have had to introduce the same logic in the CAMS2_83_Processer, and I preferred not to, because the global only_json-handling case was already coded there and I tweaked that instead, and it made more sense to me since we have just one obs network for cams2-83 anyway)
