### ISSUE TITLE
Add EMEP test data to testdata_minimal

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#121]
Tests involving lustre runs very slow taking up to a few minutes just for the 8 tests in test_read_emep.
Not sure if this is due to my internet connection (mobile hotspot, 10Mbps) or not, but it is starting to slow down development.

How do I go about adding a small EMEP dataset to the testdata at https://pyaerocom.met.no/pyaerocom-suppl/testdata-minimal.tar.gz?

**Comment by jgliss** [comment]
Thanks for thinking about tests!!! Feel free to go and add a minimal testdataset in a dedicated subdir under *modeldata* in the current testdata. This may be one or more NetCDF files, as you need it. But it would be great if you could try to keep the additional data as small as possible (I see that due to EBAS subset we already have 122MB in the current testdataset, so maybe try to stay below 10MB) ;)

You can then gzip again and send it to me so I can upload it to the webserver. 

Feel free to modify conftest.py as it suits you (e.g. by adding fixtures or skipif markers).

**Comment by jgliss** [comment]
For new development, it is good to avoid lustre dependency in tests (the current tests that depend on lustre are from times when the testdataset did not yet exist)

**Comment by ejgal** [comment]
Sounds good! It would be nice to have both daily, monthly and yearly resolution data to test on.
Selecting one variable from each frequency and only keeping the first two days/months results in 23 MB of data. This is using data from the 2019 EMEP report, which has 520x1200 lat lon grid points. Ideally I would like to have more than one variable so I can test computing auxilliary variables and unit conversions.

Are there any problems with extracting a tiny part of the grid to achive this?

**Comment by ejgal** [comment]
Extracted the first few time steps and the variables needed for the EMEP report on a 3x3 grid.
Figured out that netcdf files where dimensions length has the form `UNLIMITED (Currently X)"
use a lot more space than necessary. 

To minimize the size:
1. Do an ncdump
2. Change UNLIMITED -> actual length
3. Create a netcdf file with ncgen

See `create_subsets_emep.sh` in testdata-minimal for an example.
