### ISSUE TITLE
AerocomEvaluation/ReadGhost - only read files needed for colocation

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#144]
I'm running an AerocomEvaluation with EMEP and GHOST.
For every variable ReadGhost reads 24 files, even when I have set `start=2018`.
I was able to set the `last_file` argument in ReadGhost manually for testing purposes, but is there a way to pass this from an evaluation config file?

**Comment by ejgal** [comment]
Think I found one way:
Adding `read_opts_ungridded = {'last_file' : 12}` to obs_config.
Is this the intended way of doing this?

**Comment by jgliss** [comment]
Yes, you can do it this way. However, due to the (current) naming convention of the cached `UngriddedData` objects, it is actually not really recommended to do this as this should deactivate caching and then will reload all the time. Until we have a more sophisticated caching strategy, I think it is better to read the whole dataset. The colocation routine will crop the time interval automatically based on the input start (stop) interval (or based on the time interval covered by the model data).

**Comment by ejgal** [comment]
Okay, will keep that in mind. Thanks!
