### ISSUE TITLE
package tqdm missing in pyaerocom_env.yml?

### ISSUE THREAD

**Issue by jgriesfeller** [metno/pyaerocom#193]
Since I went through a start with an complete empty conda environment:
In order to get a working import 
```
import pyaerocom
```
at a python console I needed to install one more package:
tqdm

You might want to add that to pyaerocom_env.yml

**Comment by ejgal** [comment]
Did you use the pyaerocom_env file from master? That one is missing tqdm because it is not used in master.
The v090dev branch does use tqdm, but it is also included in the pyaerocom_env file.

I tried creating conda environments from scratch with both master and v090dev branches and can import pyaerocom with both.
The v090dev environment seem to work for running master, but not the other way around.

**Comment by ejgal** [comment]
Closing this @jgriesfeller. Feel free to reopen if the comment didn't solve your problem.
