### ISSUE TITLE
Uncorrect behavior of ReadGridded.read_var when combining options?

### ISSUE THREAD

**Issue by ejgal** [metno/pyaerocom#208]
Providing a ts_type that is not available and setting `flex_ts_type` to True when reading leads to an error even if a file is available with a different ts_type. (`DataQueryError: Could not find file match for query`)
How flexible should `flex_ts_type` be?

F.e. running these tests with input `(dict(ts_type='yearly', flex_ts_type=True), 'monthly')` fails.
The testdata includes daily and monthly files.

https://github.com/metno/pyaerocom/blob/c96dc6ebc909ff1c526f7bc846abb85f663346af/pyaerocom/io/test/test_readgridded.py#L118-L129

**Comment by jgliss** [comment]
Good question. I am a little uncertain and think for the upcoming release we should keep it like it is (since I am not sure about potential caveats that will occur silently if we change this behaviour). Originally, `flex_ts_type` was only relating to the files available, not to what is desired in the end by the user. That is why your example does not work, however, I see that the way it is currently is confusing. On the long term, perhaps it would be better for all gridded readers, if `read_var` also does the regridding before returning the `GriddedData` object, e.g. if the user specifies `ts_type='yearly', and a monthly file is available, then the monthly file is read and regridded to yearly and then this object is returned.
