### ISSUE TITLE
Applying metadata filtering when making vmrox=vmro3+vmrno2 does not work as expected

### ISSUE THREAD

**Issue by hansbrenna** [metno/pyaerocom#239]
I need to be able to use the normal metadata filtering functionality when combining O3 and NO2 to OX. The basic functionality works as far as I can tell, but I seem to only be able to use the very small number of metadata keys transferred to StationData objects to filter by. Is this correct? I get an error message listing a much smaller number of valid keys than is normally available in GHOST.

I set it up like this:

```Python
'EEA-ox-rural'        :   dict(obs_id='TEST',
                              obs_vars=['vmrox'],
                              obs_type='ungridded',
                              obs_vert_type='Surface',
                              web_interface_name='EEA-rural',
                              ts_type='daily',
                              obs_merge_how={
                                  'vmrox' : 'eval',},
                              obs_aux_requires = {
                                  'vmrox' : {
                                      'GHOST.EEA.daily' : ['vmro3','vmrno2'],
                                      }},
                              obs_aux_funs = {
                                  'vmrox' :
                                      # variables used in computation method need to be based on AeroCom
                                      # units, since the colocated StationData objects (from which the
                                      # new UngriddedData is computed, will perform AeroCom unit check
                                      # and conversion)
                                      '(GHOST.EEA.daily;vmro3+GHOST.EEA.daily;vmrno2)'
                                      },
                                  obs_aux_units = {
                                      'vmrox' : 'nmol mol-1'
                                      },
                              ignore_station_names=ignore_dict,
                              obs_filters= {**standard_filter,**rural_filter,**mountain_filter}
                              ),
```

Where the obs_filter is set up like this and works when not using the new functionality:

```Python
no2_ignore_station_names = []
o3_ignore_station_names = []
pm10_ignore_station_names = []
pm25_ignore_station_names = []

ignore_dict = {'concno2':no2_ignore_station_names,
               'vmro3':o3_ignore_station_names,
               'concpm10':pm10_ignore_station_names,
               'concpm25':pm25_ignore_station_names}

MBlandforms_to_include = ['high altitude plains','water', 'very low plateaus',
                        'plains', 'rugged lowlands','hills','high altitude plateaus',
                        'mid altitude plateaus', 'nan','lowlands', 'mid altitude plains',
                        'low plateaus',]

EEA_rural_station_types_to_include = ['background']
EEA_rural_area_types_to_include = ['rural','rural-near_city','rural-regional', 'rural-remote']


#Define filters for the obs subsets

standard_filter = {'set_flags_nan':True,}

rural_filter = {'standardised_network_provided_station_classification':EEA_rural_station_types_to_include,
                'standardised_network_provided_area_classification':EEA_rural_area_types_to_include}

mountain_filter = {'altitude':[-20,1500],
                   'ESDAC_Meybeck_landform_classification':MBlandforms_to_include}
```

**Comment by jgliss** [comment]
@hansbrenna yes, by default only the standard metadata names are transferred to the new dataset (so this is not really a bug, but intentional, as one can also combine different datasets with different metadata conventions , etc., in this new functionality). I would need to check what is needed in order to copy a set of predefined metadata keys to be copied from the original datasets to the new dataset... or apply the filters first on the original datasets before computing the new variable.

**Comment by jgliss** [comment]
@hansbrenna I can try to look at this early next week, however, would need to know from you what is most urgent: this issue, #228, or #236?

Cheers

**Comment by hansbrenna** [comment]
Maybe #236, then #228 and this issue last. It think that's a good order.

**Comment by jgliss** [comment]
@hansbrenna I worked on this in #242 (which is branched off `main-dev`). I think everything is in place, I had to re-organise a little where and when the metadata filtering of `UngriddedData` is done, since the metadata filters have to be applied to each AUX variable UngriddedData (i.e. vmro3, vmrno2) BEFORE colocating and merging these measurements to compute vmrox. So any filtering of `UngriddedData` is now done in `ReadUngridded.read` via new input arg `filter_post`. 

I tested briefly and it seems to work but I want to check tests and docs before opening PR #242 for revision. I would recommend you to checkout branch `fix-#239` and do a testrun for your case and if it works, merge that branch into your main branch.

**Comment by hansbrenna** [comment]
I'm going to test it now.

**Comment by hansbrenna** [comment]
It seems to be working :). I'll merge it into my working branch and test it together with everything else.

**Comment by jgliss** [comment]
Closing this.
