### ISSUE TITLE
New variable PM10/PM25 ratio

### ISSUE THREAD

**Issue by MichaelSchulzMETNO** [metno/pyaerocom#519]
To harmonize dust and aerosol IFS model evaluation two new variables should be included in IFS CAMS84 evaluation: The ratio of PM10/PM25 and the coarse AOD from SDA. Best consult with Sara Basart on implementation.

**Comment by MichaelSchulzMETNO** [comment]
Model output has to provide a  coarse mode od550gt1, to be compared to AERONET v3 SDA Level 1.5 coarse mode AOD.

**Comment by avaldebe** [comment]
In principle, PM10/PM25 would require a new variable definition (with units) and some kind of alias.
Coarse mode should be easier.

**Comment by jgriesfeller** [comment]
Coarse mode AOD is in pyaerocom already. Example: 
https://aeroval.met.no/evaluation.php?project=c3s&exp_name=IASI

It should also be possible to use level 1.5 of SDA. But I have not done that so far.

For the PM10/PM25 ratio I have to look into the code how derived variables are handled. Any suggestion for a name?
I guess you just want the maps? or also the same for observations and a comparison?

**Comment by jgriesfeller** [comment]
This looks relatively easy at first glance. Examples are in the aeroval config repo on gitlab.met.no. I'll try it out...

**Comment by jgriesfeller** [comment]
I could confirm that Aeronet SDA level 3 version 1.5 is usable in aeroval

The ratio of PM10/PM25 is doable for the model data via aeroval, but not for the obs data.

I will implement a proper variable in pyaerocom for both model and obs data.

**Comment by jgriesfeller** [comment]
Unfortunately pm10 and pm25 are provided by a number of observation networks (EEA, GHOST, Airnow, EBAS). Because we don't have calculated observations from read observations (the devil is in the details here), the ratio needs to be implemented in every obs network we want to use for comparison.
I will start with EEA because that is what has been used by BSC earlier. I am not sure yet where exactly the implementation will start because for EEA, the data is in different files, but there's only one instrument per per species. For EBAS on the other hand there's potentially more than one instrument per station, so one also need to perform instrument matching

**Comment by jgriesfeller** [comment]
EEA update: station IDs are not in the filenames unfortunately, so no station matching to avoid unnecessary file reads possible by just using the filenames. Considering a cache file with station codes per file name created at download time since the number of files is so large (3000 - 10000 per year and variable) at this point...TBD

**Comment by lewisblake** [comment]
@jgriesfeller it looks like you made a solid effort on this but unfortunately other things got in the way. Maybe we can discuss this during our next Pyaerocom meeting monday? It looks like we need this for CAMS2_82

**Comment by jgriesfeller** [comment]
to pick this up again (since Hilde asked for it). The current status is that the model data side is working if the ratio has been put into a model file. If we let pyaeroval do the calculation we triple model data RAM usage. The calculation is trivial to do using cdo or nco.

The observation part is not that trivial to do with pyaerocom via the API due to e.g. the EEA data storing different variables in different files.
There should be a way to also let pyaeroval do that and I even have a config file for it, but I don't remember if that actually worked. I need to try again as soon as the StoreB maintenance is over.

**Comment by jgriesfeller** [comment]
added documentation ti PPI user docs for AeroTools (https://docs.google.com/document/d/1LcAsJTDtlQFTlPQAtfllVLNwKW0SDbZwXd6uLrbbYrQ/edit)

Closing the issue therefore
