### ISSUE TITLE
region(s) should stored as an array

### ISSUE THREAD

**Issue by AugustinMortier** [metno/pyaerocom#580]
In AeroVal map json files (e.g: [AeronetL1.5-d-od550aer_Column_IFS-CTRL-od550aer.json](https://aeroval.met.no/data/cams84/eval/map/AeronetL1.5-d-od550aer_Column_IFS-CTRL-od550aer.json) ) each station has a "region" key whose value is a string. 

However, a station could belong to more than one region: e.g Ocean, and North-America.

This problem can be seen with the new [AeroVal minimap feature](https://aeroval.met.no/overall.php?project=cams84&exp_name=eval&tab=taylor). When selecting North-America, no station is highlighted since they all belong to "Oceans" (might be also a bug here).

![minimaps](https://user-images.githubusercontent.com/19610522/152380809-22cc4588-3302-4d03-88d4-1a34f9ae6ee7.png)

**Comment by jgriesfeller** [comment]
Just for the record: due to expected running time of the linked experiment, I chose to re-run [the 2021 only experiment](https://aeroval.met.no/evaluation.php?project=cams84&exp_name=eval-2021) for now. I hope that suffices for testing.
The eval experiment might need more than a day to run because it's quite large. Please let me know if it has to be the eval experiment.

**Comment by jgriesfeller** [comment]
I introduced a testing project on the web server that is only accessible if you know the URL:
https://aeroval.met.no/evaluation.php?project=testing

It has the regions in an array, but the error mentioned above persists.

**Comment by AugustinMortier** [comment]
The AeroVal minimap now can highlight stations belonging to different regions. I think this issue is solved then. Thanks!

![Screenshot from 2022-03-03 16-47-57](https://user-images.githubusercontent.com/19610522/156600058-7969231c-42ac-4f2b-8b07-518819d1eabf.png)
