### ISSUE TITLE
Inferring htap masks filtering by name

### ISSUE THREAD

**Issue by hannasv** [metno/pyaerocom#66]
Any suggestions on names for inferring htap masks filtering by name for one or multiple htap masks.
For square regions we currently use EUROPE-noMOUNTAINS. Should I add a m for mask so that it becomes EUROPEm-noMOUNTAINS?

 @jgliss @MichaelSchulzMETNO

**Comment by hannasv** [comment]
I currently have EURhtap-noMOUNTAINS.

**Comment by MichaelSchulzMETNO** [comment]
Actually - I think that EUR is the right name. I think HTAP das not need to appear in the name. I know that that is in conflict with the old names, but I am quite convinced that we will use the rectangular regions less often. So we should maybe give the EUR-rectangular region another name, such as EURqu . No Mountains is the default, no need to use that in the name neither.

**Comment by MichaelSchulzMETNO** [comment]
This has to be discussed with Jonas indeed, not sure what implications that has in terms of backward compatibility. Is it really a problem?

**Comment by jgliss** [comment]
We can discuss this next week. Maybe we can keep the old names of the current regions (e.g. EUROPE; NAMERICA, ..., used e.g. here: https://aerocom-evaluation.met.no/main.php?project=aerocom) and use shorter names for the regions defined by the masks (e.g. EUR, SEA, EAS,...). 

But for now, please do not redefine the existing names, since these regions are used in a lot of products, that are online and that I use for my paper analysis (and I use v081dev).

**Comment by MichaelSchulzMETNO** [comment]
ok, then use the short names for the new regions, and omit htap, omit also no mountains.
