### ISSUE TITLE
Automatic downloading mask.

### ISSUE THREAD

**Issue by hannasv** [metno/pyaerocom#72]
@jgliss by this:
```python
# ToDo: check for actual number of masks and not len == 0 (there may 
# be new masks in the future)
```
Do you mean that the functionality should be updated to check if there is more files available remotely than you have on your computer. Currently it checks if you have any masks on you computer and then downloads.

**Comment by jgliss** [comment]
@hannasv Yes, I think it would be better to check if all masks are available (that are located at the online source) and not that at least one mask is available, since we know how many masks there should be.

**Comment by hannasv** [comment]
Ok, I'll give this some thought before next week and I'll try to implement it then.

**Comment by hannasv** [comment]
I don't see how this should give additional functionality since the available regions are hard coded in the config.

**Comment by hannasv** [comment]
@jgliss

**Comment by jgliss** [comment]
Don't worry too much about this detail. Counting the number of .nc files in the mask directory is just a sanity check that all masks are there and can handle an Exception right away and not only in a situation where pyaerocom believes that all masks are there and than crashes to access one, e.g. because the user deleted one.

**Comment by hannasv** [comment]
Now it makes a lot more sense. I'll implement it.

**Comment by hannasv** [comment]
Pushed these changes to git now.
