### ISSUE TITLE
Random change of cache folder

### ISSUE THREAD

**Issue by dulte** [metno/pyaerocom#759]
If the user has set the CACHEDIR manually, then it might change randomly during an evaluation.

If the check_write_access function in _lowlevel_helpers fails, then the CACHEDIR getter will silently change the cachedir. Since CACHEDIR is called each time the cache is read, this has a non-zero to high probability to happen for longer evaluations, e.g. the long evaluation in CAMS2_83

**Comment by dulte** [comment]
We must either:

1. Change the check_write_access away from the multiprocessing approach it has now. (in cams2_83 I've changed to os.access(path, os.W_OK)

2. Change it so that the cache dir don't change if the check fails

3. Atleast log a warning if it happens

4. All above...

**Comment by magnusuMET** [comment]
Could you cache CACHEDIR with `https://docs.python.org/3/library/functools.html?highlight=lru#functools.cached_property`?

**Comment by dulte** [comment]
I guess that is possible. Caches all the way down...

**Comment by dulte** [comment]
After reading about this, I think that is a good idea!

**Comment by jgriesfeller** [comment]
In my opinion pyaerocom should fail with a helpful error message if the set paths cannot be used. Why should it try to solve user errors (or OS errors)?
Keep things simple.
I will solve the issue since it's really a problem for the paralleization.

We should discuss that during the next aerocom meeting.

**Comment by jgriesfeller** [comment]
I guess the root problem is that the OS is given only 0.1 seconds to determine if the location is writable. For network based paths that is often too less!
https://github.com/metno/pyaerocom/blob/4fd90c863a002cadf52a8b045fd7d0dcf76786d4/pyaerocom/_lowlevel_helpers.py#L167-L178

To be honest, the whole idea of that code is just broke because handling these things is the job of the OS, not of a user program.

If your hardware is broken, fix it!
