### ISSUE TITLE
Harmonise API and avoid diverging / duplicated code

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#77]
@jgriesfeller I think we need to put some efforts into maintaining a clean and well defined API that is modular and reuses existing code where possible. 

E.g. the module [scripts/read_colocation_files.py](https://github.com/metno/pyaerocom/blob/v090dev/pyaerocom/scripts/read_colocation_files.py) may introduce confusion I think, since it seems to be specific for satellite data (right?) and given that there is already a [ColocatedData](https://github.com/metno/pyaerocom/blob/master/pyaerocom/colocateddata.py) object which, I presume, is not the one you are using in this class? Maybe we can refactor this and you could also use the `pyaerocom.ColocatedData` class (which is essentially an `xarray.DataArray`). Since it is a reading interface, I think we should also move this class to io submodule, right?

Also, I am hoping that we all can manage to fill the minimum info in the docstrings of all classes and methods, at least with information about input and output parameters (methods) and attributes (classes) and at least a oneliner that describes what it does. It would be great if you could provide these infos for the things you are coding (I also need to get better at this). 

In general, I think we should make sure to follow a common API strategy. There is currently also diverging / repetitive code in the following modules (there may be more):

- plot/plotsitelocation.py  (e.g. used in scripts.main:cli) **vs** plot/plotcoordinates.py and plot/mapping.py (e.g. used in `UngriddedData`)
- plot/plotscatter_v0.py (e.g. used in scripts.main:cli) **vs** plot/plotscatter.py (e.g. used in `ColocatedData`)

The latter plotting method for instance, is doing the full colocation within the method. This should be outsourced and should use one of the [pyaerocom colocation methods](https://github.com/metno/pyaerocom/blob/v090dev/pyaerocom/colocation.py) that return a `ColocatedData` object, which can then be used to do the scatter plot (e.g. via `ColocatedData.plot_scatter` method, e.g. [see here](https://pyaerocom.met.no/tutorials.html#monthly-world-no-mountains)).

What do you think?

**Comment by jgriesfeller** [comment]
The satellite stuff is a mess right now and mixes several things (e.g. there is some plotting involved as well). It's orientated at getting things done at this point and I am not entirely sure yet where this will end. I don't have a real plan.
Since it's not visible in the API unless the coda package is installed, I think this is not very important at this point. But due to project commitments, the Satellite stuff has to be in pyaerocom.
The current objects also do not entirely fill my needs, e.g. due to memory constraints (e.g a day of Sentinel5p data has several GB of L2 data). In addition, the ungridded data I have is not station based.
The structure is also not finished (e.g. read_colocation_files.py is essentially a file from an earlier project). But this is a development branch, right? If you do not want something in master, then don't merge it there. At the end we don't mange to do proper project planning, so the guy who programmes most gets to decide (you). My contribution is small at the end.

**Comment by jgliss** [comment]
Okay, thanks. Maybe we could have a meeting where we review what you did and what may be useful to incorporate within the API (i.e. low hanging fruits). I think this is very useful work you do, and apart from it being an important contribution to pyaerocom, it could make the current API better / more flexible as well (e.g. maybe we can generalise the `UngriddedData` object so that it fulfills your needs).
