### ISSUE TITLE
ts_type, colocation

### ISSUE THREAD

**Issue by hildefagerli** [metno/pyaerocom#811]
When you want to have a target resolution of your obs-mod comparison of monthly (including both daily and weekly observations), and you have daily model data, you want to co-locate on the highest resolution possible for each data set. For instance, you want to co-locate daily obs and daily mod, but for the weekly observations you would like to co-locate on weekly.

However, it looks like pyaerocom cannot do that. E.g. for 2022-reporting EMEP evaluation for EC:
https://aeroval.met.no/evaluation.php?project=emep&exp_name=2022-reporting&station=Observatoire+Perenne+de+l%27Environnement&par=concCecpm25&obs=EBAS-d#

You can see that the monthly averages in the EBAS-d is different from EBAS-m for model (because pyaerocom use the monthly value, not the average of the daily colocated values in EBAS-m).

One should have a target resolution that does not need to be the same as the co-location resolution, and one should be able to co-locate on different resolutions depending on the resolution of the observations. Maybe this is possible already if the config is set up right, but I do not think so. Is this possible to check?

**Comment by jgriesfeller** [comment]
This is not trivial at all. 
So far the colocation basically works on the middle points only (as far as I am aware) with the time step size in mind.
I think to do this correctly, we would need a colocation that takes the start and the end time into account. This is definitively outside of the scope of the currently used xarray and pandas packages and means we have to write our own time based colocation routines since I am not aware of any existing Python package that can do this.
We might want to have a look at the cis tools (http://www.cistools.net/)
